//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace principal.ServiceRefUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/Usuarios_SOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoEmpleado {
            get {
                return this.ApellidoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoEmpleadoField, value) != true)) {
                    this.ApellidoEmpleadoField = value;
                    this.RaisePropertyChanged("ApellidoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaEmpleado {
            get {
                return this.AreaEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaEmpleadoField, value) != true)) {
                    this.AreaEmpleadoField = value;
                    this.RaisePropertyChanged("AreaEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CargoEmpleado {
            get {
                return this.CargoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoEmpleadoField, value) != true)) {
                    this.CargoEmpleadoField = value;
                    this.RaisePropertyChanged("CargoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodEmpleado {
            get {
                return this.CodEmpleadoField;
            }
            set {
                if ((this.CodEmpleadoField.Equals(value) != true)) {
                    this.CodEmpleadoField = value;
                    this.RaisePropertyChanged("CodEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoEmpleado {
            get {
                return this.CorreoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoEmpleadoField, value) != true)) {
                    this.CorreoEmpleadoField = value;
                    this.RaisePropertyChanged("CorreoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado {
            get {
                return this.NombreEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpleadoField, value) != true)) {
                    this.NombreEmpleadoField = value;
                    this.RaisePropertyChanged("NombreEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoEmpleado {
            get {
                return this.TelefonoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoEmpleadoField, value) != true)) {
                    this.TelefonoEmpleadoField = value;
                    this.RaisePropertyChanged("TelefonoEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRefUser.IEmpleados")]
    public interface IEmpleados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleados/CrearEmpleado", ReplyAction="http://tempuri.org/IEmpleados/CrearEmpleadoResponse")]
        principal.ServiceRefUser.Empleado CrearEmpleado(string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleados/CrearEmpleado", ReplyAction="http://tempuri.org/IEmpleados/CrearEmpleadoResponse")]
        System.IAsyncResult BeginCrearEmpleado(string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, System.AsyncCallback callback, object asyncState);
        
        principal.ServiceRefUser.Empleado EndCrearEmpleado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleados/ObtenerEmpleado", ReplyAction="http://tempuri.org/IEmpleados/ObtenerEmpleadoResponse")]
        principal.ServiceRefUser.Empleado ObtenerEmpleado(int CodEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleados/ObtenerEmpleado", ReplyAction="http://tempuri.org/IEmpleados/ObtenerEmpleadoResponse")]
        System.IAsyncResult BeginObtenerEmpleado(int CodEmpleado, System.AsyncCallback callback, object asyncState);
        
        principal.ServiceRefUser.Empleado EndObtenerEmpleado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleados/ModificarEmpleado", ReplyAction="http://tempuri.org/IEmpleados/ModificarEmpleadoResponse")]
        principal.ServiceRefUser.Empleado ModificarEmpleado(int CodEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleados/ModificarEmpleado", ReplyAction="http://tempuri.org/IEmpleados/ModificarEmpleadoResponse")]
        System.IAsyncResult BeginModificarEmpleado(int CodEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, System.AsyncCallback callback, object asyncState);
        
        principal.ServiceRefUser.Empleado EndModificarEmpleado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleados/EliminarEmpleado", ReplyAction="http://tempuri.org/IEmpleados/EliminarEmpleadoResponse")]
        principal.ServiceRefUser.Empleado EliminarEmpleado(int CodEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleados/EliminarEmpleado", ReplyAction="http://tempuri.org/IEmpleados/EliminarEmpleadoResponse")]
        System.IAsyncResult BeginEliminarEmpleado(int CodEmpleado, System.AsyncCallback callback, object asyncState);
        
        principal.ServiceRefUser.Empleado EndEliminarEmpleado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleados/ListarEmpleados", ReplyAction="http://tempuri.org/IEmpleados/ListarEmpleadosResponse")]
        principal.ServiceRefUser.Empleado[] ListarEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEmpleados/ListarEmpleados", ReplyAction="http://tempuri.org/IEmpleados/ListarEmpleadosResponse")]
        System.IAsyncResult BeginListarEmpleados(System.AsyncCallback callback, object asyncState);
        
        principal.ServiceRefUser.Empleado[] EndListarEmpleados(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadosChannel : principal.ServiceRefUser.IEmpleados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrearEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CrearEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public principal.ServiceRefUser.Empleado Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((principal.ServiceRefUser.Empleado)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public principal.ServiceRefUser.Empleado Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((principal.ServiceRefUser.Empleado)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModificarEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ModificarEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public principal.ServiceRefUser.Empleado Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((principal.ServiceRefUser.Empleado)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EliminarEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EliminarEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public principal.ServiceRefUser.Empleado Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((principal.ServiceRefUser.Empleado)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarEmpleadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarEmpleadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public principal.ServiceRefUser.Empleado[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((principal.ServiceRefUser.Empleado[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadosClient : System.ServiceModel.ClientBase<principal.ServiceRefUser.IEmpleados>, principal.ServiceRefUser.IEmpleados {
        
        private BeginOperationDelegate onBeginCrearEmpleadoDelegate;
        
        private EndOperationDelegate onEndCrearEmpleadoDelegate;
        
        private System.Threading.SendOrPostCallback onCrearEmpleadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerEmpleadoDelegate;
        
        private EndOperationDelegate onEndObtenerEmpleadoDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerEmpleadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificarEmpleadoDelegate;
        
        private EndOperationDelegate onEndModificarEmpleadoDelegate;
        
        private System.Threading.SendOrPostCallback onModificarEmpleadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginEliminarEmpleadoDelegate;
        
        private EndOperationDelegate onEndEliminarEmpleadoDelegate;
        
        private System.Threading.SendOrPostCallback onEliminarEmpleadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarEmpleadosDelegate;
        
        private EndOperationDelegate onEndListarEmpleadosDelegate;
        
        private System.Threading.SendOrPostCallback onListarEmpleadosCompletedDelegate;
        
        public EmpleadosClient() {
        }
        
        public EmpleadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CrearEmpleadoCompletedEventArgs> CrearEmpleadoCompleted;
        
        public event System.EventHandler<ObtenerEmpleadoCompletedEventArgs> ObtenerEmpleadoCompleted;
        
        public event System.EventHandler<ModificarEmpleadoCompletedEventArgs> ModificarEmpleadoCompleted;
        
        public event System.EventHandler<EliminarEmpleadoCompletedEventArgs> EliminarEmpleadoCompleted;
        
        public event System.EventHandler<ListarEmpleadosCompletedEventArgs> ListarEmpleadosCompleted;
        
        public principal.ServiceRefUser.Empleado CrearEmpleado(string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado) {
            return base.Channel.CrearEmpleado(ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCrearEmpleado(string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCrearEmpleado(ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public principal.ServiceRefUser.Empleado EndCrearEmpleado(System.IAsyncResult result) {
            return base.Channel.EndCrearEmpleado(result);
        }
        
        private System.IAsyncResult OnBeginCrearEmpleado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ApellidoEmpleado = ((string)(inValues[0]));
            string CorreoEmpleado = ((string)(inValues[1]));
            string CargoEmpleado = ((string)(inValues[2]));
            string TelefonoEmpleado = ((string)(inValues[3]));
            string AreaEmpleado = ((string)(inValues[4]));
            return this.BeginCrearEmpleado(ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado, callback, asyncState);
        }
        
        private object[] OnEndCrearEmpleado(System.IAsyncResult result) {
            principal.ServiceRefUser.Empleado retVal = this.EndCrearEmpleado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCrearEmpleadoCompleted(object state) {
            if ((this.CrearEmpleadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CrearEmpleadoCompleted(this, new CrearEmpleadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CrearEmpleadoAsync(string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado) {
            this.CrearEmpleadoAsync(ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado, null);
        }
        
        public void CrearEmpleadoAsync(string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, object userState) {
            if ((this.onBeginCrearEmpleadoDelegate == null)) {
                this.onBeginCrearEmpleadoDelegate = new BeginOperationDelegate(this.OnBeginCrearEmpleado);
            }
            if ((this.onEndCrearEmpleadoDelegate == null)) {
                this.onEndCrearEmpleadoDelegate = new EndOperationDelegate(this.OnEndCrearEmpleado);
            }
            if ((this.onCrearEmpleadoCompletedDelegate == null)) {
                this.onCrearEmpleadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCrearEmpleadoCompleted);
            }
            base.InvokeAsync(this.onBeginCrearEmpleadoDelegate, new object[] {
                        ApellidoEmpleado,
                        CorreoEmpleado,
                        CargoEmpleado,
                        TelefonoEmpleado,
                        AreaEmpleado}, this.onEndCrearEmpleadoDelegate, this.onCrearEmpleadoCompletedDelegate, userState);
        }
        
        public principal.ServiceRefUser.Empleado ObtenerEmpleado(int CodEmpleado) {
            return base.Channel.ObtenerEmpleado(CodEmpleado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerEmpleado(int CodEmpleado, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerEmpleado(CodEmpleado, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public principal.ServiceRefUser.Empleado EndObtenerEmpleado(System.IAsyncResult result) {
            return base.Channel.EndObtenerEmpleado(result);
        }
        
        private System.IAsyncResult OnBeginObtenerEmpleado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int CodEmpleado = ((int)(inValues[0]));
            return this.BeginObtenerEmpleado(CodEmpleado, callback, asyncState);
        }
        
        private object[] OnEndObtenerEmpleado(System.IAsyncResult result) {
            principal.ServiceRefUser.Empleado retVal = this.EndObtenerEmpleado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerEmpleadoCompleted(object state) {
            if ((this.ObtenerEmpleadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerEmpleadoCompleted(this, new ObtenerEmpleadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerEmpleadoAsync(int CodEmpleado) {
            this.ObtenerEmpleadoAsync(CodEmpleado, null);
        }
        
        public void ObtenerEmpleadoAsync(int CodEmpleado, object userState) {
            if ((this.onBeginObtenerEmpleadoDelegate == null)) {
                this.onBeginObtenerEmpleadoDelegate = new BeginOperationDelegate(this.OnBeginObtenerEmpleado);
            }
            if ((this.onEndObtenerEmpleadoDelegate == null)) {
                this.onEndObtenerEmpleadoDelegate = new EndOperationDelegate(this.OnEndObtenerEmpleado);
            }
            if ((this.onObtenerEmpleadoCompletedDelegate == null)) {
                this.onObtenerEmpleadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerEmpleadoCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerEmpleadoDelegate, new object[] {
                        CodEmpleado}, this.onEndObtenerEmpleadoDelegate, this.onObtenerEmpleadoCompletedDelegate, userState);
        }
        
        public principal.ServiceRefUser.Empleado ModificarEmpleado(int CodEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado) {
            return base.Channel.ModificarEmpleado(CodEmpleado, ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginModificarEmpleado(int CodEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificarEmpleado(CodEmpleado, ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public principal.ServiceRefUser.Empleado EndModificarEmpleado(System.IAsyncResult result) {
            return base.Channel.EndModificarEmpleado(result);
        }
        
        private System.IAsyncResult OnBeginModificarEmpleado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int CodEmpleado = ((int)(inValues[0]));
            string ApellidoEmpleado = ((string)(inValues[1]));
            string CorreoEmpleado = ((string)(inValues[2]));
            string CargoEmpleado = ((string)(inValues[3]));
            string TelefonoEmpleado = ((string)(inValues[4]));
            string AreaEmpleado = ((string)(inValues[5]));
            return this.BeginModificarEmpleado(CodEmpleado, ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado, callback, asyncState);
        }
        
        private object[] OnEndModificarEmpleado(System.IAsyncResult result) {
            principal.ServiceRefUser.Empleado retVal = this.EndModificarEmpleado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnModificarEmpleadoCompleted(object state) {
            if ((this.ModificarEmpleadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ModificarEmpleadoCompleted(this, new ModificarEmpleadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ModificarEmpleadoAsync(int CodEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado) {
            this.ModificarEmpleadoAsync(CodEmpleado, ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado, null);
        }
        
        public void ModificarEmpleadoAsync(int CodEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, object userState) {
            if ((this.onBeginModificarEmpleadoDelegate == null)) {
                this.onBeginModificarEmpleadoDelegate = new BeginOperationDelegate(this.OnBeginModificarEmpleado);
            }
            if ((this.onEndModificarEmpleadoDelegate == null)) {
                this.onEndModificarEmpleadoDelegate = new EndOperationDelegate(this.OnEndModificarEmpleado);
            }
            if ((this.onModificarEmpleadoCompletedDelegate == null)) {
                this.onModificarEmpleadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificarEmpleadoCompleted);
            }
            base.InvokeAsync(this.onBeginModificarEmpleadoDelegate, new object[] {
                        CodEmpleado,
                        ApellidoEmpleado,
                        CorreoEmpleado,
                        CargoEmpleado,
                        TelefonoEmpleado,
                        AreaEmpleado}, this.onEndModificarEmpleadoDelegate, this.onModificarEmpleadoCompletedDelegate, userState);
        }
        
        public principal.ServiceRefUser.Empleado EliminarEmpleado(int CodEmpleado) {
            return base.Channel.EliminarEmpleado(CodEmpleado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEliminarEmpleado(int CodEmpleado, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEliminarEmpleado(CodEmpleado, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public principal.ServiceRefUser.Empleado EndEliminarEmpleado(System.IAsyncResult result) {
            return base.Channel.EndEliminarEmpleado(result);
        }
        
        private System.IAsyncResult OnBeginEliminarEmpleado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int CodEmpleado = ((int)(inValues[0]));
            return this.BeginEliminarEmpleado(CodEmpleado, callback, asyncState);
        }
        
        private object[] OnEndEliminarEmpleado(System.IAsyncResult result) {
            principal.ServiceRefUser.Empleado retVal = this.EndEliminarEmpleado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEliminarEmpleadoCompleted(object state) {
            if ((this.EliminarEmpleadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EliminarEmpleadoCompleted(this, new EliminarEmpleadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EliminarEmpleadoAsync(int CodEmpleado) {
            this.EliminarEmpleadoAsync(CodEmpleado, null);
        }
        
        public void EliminarEmpleadoAsync(int CodEmpleado, object userState) {
            if ((this.onBeginEliminarEmpleadoDelegate == null)) {
                this.onBeginEliminarEmpleadoDelegate = new BeginOperationDelegate(this.OnBeginEliminarEmpleado);
            }
            if ((this.onEndEliminarEmpleadoDelegate == null)) {
                this.onEndEliminarEmpleadoDelegate = new EndOperationDelegate(this.OnEndEliminarEmpleado);
            }
            if ((this.onEliminarEmpleadoCompletedDelegate == null)) {
                this.onEliminarEmpleadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEliminarEmpleadoCompleted);
            }
            base.InvokeAsync(this.onBeginEliminarEmpleadoDelegate, new object[] {
                        CodEmpleado}, this.onEndEliminarEmpleadoDelegate, this.onEliminarEmpleadoCompletedDelegate, userState);
        }
        
        public principal.ServiceRefUser.Empleado[] ListarEmpleados() {
            return base.Channel.ListarEmpleados();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListarEmpleados(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarEmpleados(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public principal.ServiceRefUser.Empleado[] EndListarEmpleados(System.IAsyncResult result) {
            return base.Channel.EndListarEmpleados(result);
        }
        
        private System.IAsyncResult OnBeginListarEmpleados(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginListarEmpleados(callback, asyncState);
        }
        
        private object[] OnEndListarEmpleados(System.IAsyncResult result) {
            principal.ServiceRefUser.Empleado[] retVal = this.EndListarEmpleados(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarEmpleadosCompleted(object state) {
            if ((this.ListarEmpleadosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarEmpleadosCompleted(this, new ListarEmpleadosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarEmpleadosAsync() {
            this.ListarEmpleadosAsync(null);
        }
        
        public void ListarEmpleadosAsync(object userState) {
            if ((this.onBeginListarEmpleadosDelegate == null)) {
                this.onBeginListarEmpleadosDelegate = new BeginOperationDelegate(this.OnBeginListarEmpleados);
            }
            if ((this.onEndListarEmpleadosDelegate == null)) {
                this.onEndListarEmpleadosDelegate = new EndOperationDelegate(this.OnEndListarEmpleados);
            }
            if ((this.onListarEmpleadosCompletedDelegate == null)) {
                this.onListarEmpleadosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarEmpleadosCompleted);
            }
            base.InvokeAsync(this.onBeginListarEmpleadosDelegate, null, this.onEndListarEmpleadosDelegate, this.onListarEmpleadosCompletedDelegate, userState);
        }
    }
}
