//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace principal.ServiceEstadoPrioridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/Usuarios_SOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoTicket {
            get {
                return this.EstadoTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoTicketField, value) != true)) {
                    this.EstadoTicketField = value;
                    this.RaisePropertyChanged("EstadoTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prioridad", Namespace="http://schemas.datacontract.org/2004/07/Usuarios_SOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Prioridad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrioridadTicketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrioridadTicket {
            get {
                return this.PrioridadTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.PrioridadTicketField, value) != true)) {
                    this.PrioridadTicketField = value;
                    this.RaisePropertyChanged("PrioridadTicket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEstadoPrioridad.IEstadosPrioridad")]
    public interface IEstadosPrioridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadosPrioridad/ObtenerEstado", ReplyAction="http://tempuri.org/IEstadosPrioridad/ObtenerEstadoResponse")]
        principal.ServiceEstadoPrioridad.Estado ObtenerEstado(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadosPrioridad/ObtenerPrioridad", ReplyAction="http://tempuri.org/IEstadosPrioridad/ObtenerPrioridadResponse")]
        principal.ServiceEstadoPrioridad.Prioridad ObtenerPrioridad(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstadosPrioridadChannel : principal.ServiceEstadoPrioridad.IEstadosPrioridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadosPrioridadClient : System.ServiceModel.ClientBase<principal.ServiceEstadoPrioridad.IEstadosPrioridad>, principal.ServiceEstadoPrioridad.IEstadosPrioridad {
        
        public EstadosPrioridadClient() {
        }
        
        public EstadosPrioridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadosPrioridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadosPrioridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadosPrioridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public principal.ServiceEstadoPrioridad.Estado ObtenerEstado(int value) {
            return base.Channel.ObtenerEstado(value);
        }
        
        public principal.ServiceEstadoPrioridad.Prioridad ObtenerPrioridad(int value) {
            return base.Channel.ObtenerPrioridad(value);
        }
    }
}
