//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace principal.RegistroTicketsServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuardaTicket", Namespace="http://schemas.datacontract.org/2004/07/RegistrodeTickets.Dominio")]
    [System.SerializableAttribute()]
    public partial class GuardaTicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime F_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_ticketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Obs_atencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoEmpleado {
            get {
                return this.ApellidoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoEmpleadoField, value) != true)) {
                    this.ApellidoEmpleadoField = value;
                    this.RaisePropertyChanged("ApellidoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaEmpleado {
            get {
                return this.AreaEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaEmpleadoField, value) != true)) {
                    this.AreaEmpleadoField = value;
                    this.RaisePropertyChanged("AreaEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AsuntoTicket {
            get {
                return this.AsuntoTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoTicketField, value) != true)) {
                    this.AsuntoTicketField = value;
                    this.RaisePropertyChanged("AsuntoTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CargoEmpleado {
            get {
                return this.CargoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoEmpleadoField, value) != true)) {
                    this.CargoEmpleadoField = value;
                    this.RaisePropertyChanged("CargoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodEmpleado {
            get {
                return this.CodEmpleadoField;
            }
            set {
                if ((this.CodEmpleadoField.Equals(value) != true)) {
                    this.CodEmpleadoField = value;
                    this.RaisePropertyChanged("CodEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoEmpleado {
            get {
                return this.CorreoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoEmpleadoField, value) != true)) {
                    this.CorreoEmpleadoField = value;
                    this.RaisePropertyChanged("CorreoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime F_creacion {
            get {
                return this.F_creacionField;
            }
            set {
                if ((this.F_creacionField.Equals(value) != true)) {
                    this.F_creacionField = value;
                    this.RaisePropertyChanged("F_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_ticket {
            get {
                return this.N_ticketField;
            }
            set {
                if ((this.N_ticketField.Equals(value) != true)) {
                    this.N_ticketField = value;
                    this.RaisePropertyChanged("N_ticket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado {
            get {
                return this.NombreEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpleadoField, value) != true)) {
                    this.NombreEmpleadoField = value;
                    this.RaisePropertyChanged("NombreEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obs_atencion {
            get {
                return this.Obs_atencionField;
            }
            set {
                if ((object.ReferenceEquals(this.Obs_atencionField, value) != true)) {
                    this.Obs_atencionField = value;
                    this.RaisePropertyChanged("Obs_atencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionTicket {
            get {
                return this.ObservacionTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionTicketField, value) != true)) {
                    this.ObservacionTicketField = value;
                    this.RaisePropertyChanged("ObservacionTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoEmpleado {
            get {
                return this.TelefonoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoEmpleadoField, value) != true)) {
                    this.TelefonoEmpleadoField = value;
                    this.RaisePropertyChanged("TelefonoEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistroTicketsServices.IGuardaTickets")]
    public interface IGuardaTickets {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardaTickets/InsertarTicket", ReplyAction="http://tempuri.org/IGuardaTickets/InsertarTicketResponse")]
        principal.RegistroTicketsServices.GuardaTicket InsertarTicket(int N_Ticket, System.DateTime F_creacion, string Estado, int CodEmpleado, string NombreEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, string AsuntoTicket, string ObservacionTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardaTickets/ObtenerTicket", ReplyAction="http://tempuri.org/IGuardaTickets/ObtenerTicketResponse")]
        principal.RegistroTicketsServices.GuardaTicket ObtenerTicket(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardaTickets/ModificarTicket", ReplyAction="http://tempuri.org/IGuardaTickets/ModificarTicketResponse")]
        principal.RegistroTicketsServices.GuardaTicket ModificarTicket(int Id, int N_Ticket, System.DateTime F_creacion, string Estado, int CodEmpleado, string NombreEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, string AsuntoTicket, string ObservacionTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardaTickets/EliminarTicket", ReplyAction="http://tempuri.org/IGuardaTickets/EliminarTicketResponse")]
        principal.RegistroTicketsServices.GuardaTicket EliminarTicket(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardaTickets/ListarTicket", ReplyAction="http://tempuri.org/IGuardaTickets/ListarTicketResponse")]
        principal.RegistroTicketsServices.GuardaTicket[] ListarTicket();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuardaTicketsChannel : principal.RegistroTicketsServices.IGuardaTickets, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuardaTicketsClient : System.ServiceModel.ClientBase<principal.RegistroTicketsServices.IGuardaTickets>, principal.RegistroTicketsServices.IGuardaTickets {
        
        public GuardaTicketsClient() {
        }
        
        public GuardaTicketsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuardaTicketsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuardaTicketsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuardaTicketsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public principal.RegistroTicketsServices.GuardaTicket InsertarTicket(int N_Ticket, System.DateTime F_creacion, string Estado, int CodEmpleado, string NombreEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, string AsuntoTicket, string ObservacionTicket) {
            return base.Channel.InsertarTicket(N_Ticket, F_creacion, Estado, CodEmpleado, NombreEmpleado, ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado, AsuntoTicket, ObservacionTicket);
        }
        
        public principal.RegistroTicketsServices.GuardaTicket ObtenerTicket(int Id) {
            return base.Channel.ObtenerTicket(Id);
        }
        
        public principal.RegistroTicketsServices.GuardaTicket ModificarTicket(int Id, int N_Ticket, System.DateTime F_creacion, string Estado, int CodEmpleado, string NombreEmpleado, string ApellidoEmpleado, string CorreoEmpleado, string CargoEmpleado, string TelefonoEmpleado, string AreaEmpleado, string AsuntoTicket, string ObservacionTicket) {
            return base.Channel.ModificarTicket(Id, N_Ticket, F_creacion, Estado, CodEmpleado, NombreEmpleado, ApellidoEmpleado, CorreoEmpleado, CargoEmpleado, TelefonoEmpleado, AreaEmpleado, AsuntoTicket, ObservacionTicket);
        }
        
        public principal.RegistroTicketsServices.GuardaTicket EliminarTicket(int Id) {
            return base.Channel.EliminarTicket(Id);
        }
        
        public principal.RegistroTicketsServices.GuardaTicket[] ListarTicket() {
            return base.Channel.ListarTicket();
        }
    }
}
